### PR TITLE
Major restructuring

### PR DESCRIPTION
**Pull request by jedi4ever**
Hey , I know this a very large commit. It's a major restructuring for I believe is a better way of accessing the calls.

Please do me the favor of taking your time to read this through. I'll be happy to change comments. But I do hope changes get picked up in the mainstream branch...

I see you have reworked the specs, I'm afraid these will need to be rewritten for these restructurings.

Thanks for your patience, 

Patrick

### CODE REVIEW

**Comment by jedi4ever** [comment]
hey, don't mean to hurry you, but fog is going to release in 2 weeks, and I'm hoping this update gets done,to make the vmfusion provider work

**Comment by nigelkersten** [comment]
I'd like to add support for Fusion 4 to fission, but it doesn't seem to make sense before a decision gets made on this, is there anything anyone else can do to help review this extensive commit series?

**Comment by thbishop** [comment]
Yeah, I would hold off on trying to add fusion 4 support until this is worked out.  I should have a beta with these changes out later this week.

**Comment by thbishop** [comment]
I just pushed 0.4.beta.1 with the majority of these changes.  Have a look and let me know what you think.

**Comment by jedi4ever** [comment]
sweet! I'll have a play with it next week!

**Comment by nigelkersten** [comment]
Awesome. I'll start looking at fusion 4 support in the next few weeks.

**Comment by thbishop** [comment]
@jedi4ever have you had a chance to give the beta a run?

**Comment by jedi4ever** [comment]
Not yet,planned currently for next week. thanks for the update by the way

**Comment by ody** [comment]
Been trying to work with the beta for about a week now.  Only major issue is starting VMs in headless mode.  How ever vmrun is dealing with stdout, ruby doesn't like it.  Any IO stream that is trying to read the command's stdout just waits.  Been unable to find a way around it short of redirecting all stdout to /dev/null.  Looks like the process that vmrun is forking is using the stdout opened by vmrun, so if I start a VM with nogui in terminal A and shut it down in terminal B I get stdout in terminal A when the VM goes down.

More of the changes associated with commit 47783d4 would be useful.  Having to run the 'Fission::CLI.execute(['status'])' and redirect stdout to dump the output_printf, just to get a structured data object of VM statuses is a bit wasteful.

**Comment by thbishop** [comment]
@ody What version of ruby and fusion are you running?  Can you provide a gist of what you're seeing with the stdout issue?  I'm not experiencing that behavior on my system.

Would something like the following meet your needs for getting the status of all VMs?

``` ruby
response = VM.status_of_all # or VM.all_with_status
response.data
# =>  { 'foo' => 'running', 'bar' => 'suspended' }
```

The status command implementation in 47783d4b584507b3f1313e1981b06d0e3cda14e3 could be very slow (as vmrun list was run for every VM).  As such, the new implementation is a bit more involved (https://github.com/thbishop/fission/blob/v0.4.0.beta.2/lib/fission/command/status.rb).

Are there other specific changes from 47783d4b584507b3f1313e1981b06d0e3cda14e3 which are not in 0.4.0.beta.2 that would be useful?

Thanks for the feedback.

**Comment by ody** [comment]
@thbishop Yes.  The ability to do what you outline would be sufficient.  The current implementation in 0.4.0.beta.2 is deficient because it does the creation of the data structure and the output in the same method.

```
ruby-1.8.7-p352 :004 > Fission::CLI.execute(['status'])
pe-centos4        [not running]
pe-centos5        [not running]
pe-centos6        [not running]
pe-debian5        [not running]
pe-debian6        [not running]
pe-sles11         [not running]
pe-solaris10      [not running]
pe-ubuntu-lucid   [not running]
 => [#<Fission::VM:0x1079b5ea8 @name="pe-centos4">, #<Fission::VM:0x1079b5e30 @name="pe-centos5">, #<Fission::VM:0x1079b5db8 @name="pe-centos6">, #<Fission::VM:0x1079b5d40 @name="pe-debian5">, #<Fission::VM:0x1079b5cc8 @name="pe-debian6">, #<Fission::VM:0x1079b5c50 @name="pe-sles11">, #<Fission::VM:0x1079b5bd8 @name="pe-solaris10">, #<Fission::VM:0x1079b5b60 @name="pe-ubuntu-lucid">]
```

Currently to get and work on just that data structure I must throw away standard out of re-implement the code in the execute method.

It might be quicker more and more efficient if you could point our your concerns with jedi4ever's pull request and we can address those one by one instead of I pointing out what I would like from the commit functionality-wise and you reimplementing the functionality.

**Comment by thbishop** [comment]
I've added VM.all_with_status (6860c19935cbe36e3b08b15db032d49ba45d3b40) and released 0.4.0.beta.3.

I believe all of the functionality from this pull request has already been included in the 0.4.0 betas (although some of the interfaces/signatures may not be exactly the same).

Here are _some_ examples of the differences:
- Replaced exception based flow control with Response object
- Removed @vm.resume (@vm.start accomplishes the goal without introducing another method; I don't see the value here)
- Replaced @vm.halt with @vm.stop :hard => true
- Return all macs for @vm.mac_addresses
- Replaced @vm.ip_address with @vm.network_info
- Added tests for all of the changes

I didn't merge the pull request directly largely due to the combination of a vast number/scope of changes and lack of tests.  I also didn't want to go down the route of using exceptions for flow control.  Given that the bulk of this functionality has already been integrated, I'm interested in understanding if the functionality is sufficient.

I apologize for not being clear when referring to the stdout issue.  Can you provide a gist of the issue you're seeing with stdout between terminals when starting/stopping a headless VM?  I'm not seeing this behavior on either of my systems.

Thanks.

**Comment by ody** [comment]
I will open an actually ticket for the stdout of vmrun issue I am having.  It is quite annoying since it requires me to modify fission to do 1>/dev/null.  Will also convert my work of your the new beta today and see how everything works.

**Comment by thbishop** [comment]
@jedi4ever have you been able to give these changes a try?

**Comment by thbishop** [comment]
I've released 0.4.0 with these changes.  If there are any issues with the lib interface, please open a ticket.  Thanks @jedi4ever and @ody for all of your help with this.  It's very much appreciated.

**Pull request closed without merging**
