### PR TITLE
Retrieve ip_address / mac_address /state from a vm

### PR DESCRIPTION
**Pull request by jedi4ever**
Note ip/mac information will only work for autogenerate, vmware fusion assigned dhcp address

### CODE REVIEW

**Comment by jedi4ever** [comment]
Now the state can be queried on the vm object

**Comment by thbishop** [comment]
Thanks for the pull request.  I'll look at this for 0.4.0.

**Comment by jedi4ever** [comment]
How do you think the timing will work for the new release?

**Comment by thbishop** [comment]
I'm going to release 0.3.0 this weekend.  I'm hoping that 0.4.0 would follow within a week or two.

**Comment by jedi4ever** [comment]
Sounds great! Let me know if I can help with testing somethings

**Comment by jedi4ever** [comment]
you can forget about this pull request, the three is now defunct

**Pull request closed without merging**
